apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enterprise-app.fullname" . }}-secret
  labels:
    {{- include "enterprise-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
