apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amalpk531/Enterprise-Deployment-Platform-gitops.git
    targetRevision: HEAD
    path: helm/enterprise-app
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: enterprise-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true