apiVersion: v1
kind: Service
metadata:
  name: enterprise-app
  namespace: enterprise-app-prod
spec:
  selector:
    app: enterprise-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP